### ISSUE TITLE
Error in HTML page when last line of CSV is empty

### ISSUE THREAD

**Issue by bram85** [vividvilla/csvtotable#14]
When the last row of a CSV has a trailing newline, i.e. an empty line at the end, then the HTML page displays an error popup upon load:

> DataTables warning: table id=table - Requested unknown parameter '0' for row 11227, column 0. For more information about this error, please see http://datatables.net/tn/4

**Comment by vividvilla** [comment]
Thanks for reporting. Its fixed in [latest release](https://github.com/vividvilla/csvtotable/releases/tag/2.1.1).
