### ISSUE TITLE
hello  I use your code  to write a new soft

### ISSUE THREAD

**Issue by yxxhero** [vividvilla/csvtotable#20]
this soft is that  mysql >>> html ,I get data from mysql 
so  can  I delivered delivered  my soft on githup?

**Comment by chfw** [comment]
@yxxhero , this library is under MIT license. should be OK.

**Comment by vividvilla** [comment]
As @chfw said you can distribute your library without any consent as long as you release your library also under MIT license. Please do share the library link here and it will be nice gesture if you add credits to this project.
