### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mData' of undefined

### ISSUE THREAD

**Issue by roberdam** [vividvilla/csvtotable#3]
Attached the CSV
[data.zip](https://github.com/vividvilla/csvtotable/files/1130986/data.zip)

**Comment by crazymerlyn** [comment]
This is happening due to the quotes in your data. By default, `csvtotable` uses `|` as the quoting character instead of `"`.
Using `csvtotable -q '"' data.csv data.html` will render the page properly.

**Comment by roberdam** [comment]
Works great now!, thanks @crazymerlyn !
