### ISSUE TITLE
is this repo still alive?

### ISSUE THREAD

**Issue by hemangjoshi37a** [vividvilla/csvtotable#36]
Why there are so many unresolved issues and unmerged PRs? If you can give me write access I can help you develop this repo.

**Comment by candideu** [comment]
Doesn't look like it is... Are you working on a fork? Looks like there's one with Excel in mind, but it hasn't been updated in a while too: https://github.com/pyexcel/excel2table

**Comment by hemangjoshi37a** [comment]
@candideu not working on a fork but this is really good repo.

**Comment by vividvilla** [comment]
I haven't been able to work on this project for a while but please feel free to send PR and I will review and merge.

**Comment by hemangjoshi37a** [comment]
Yeah for sure
