### ISSUE TITLE
Issue with conversion...

### ISSUE THREAD

**Issue by infracritical** [vividvilla/csvtotable#9]
Am getting an "Aborted!" error message.

I saved the file as UTF-8 text, then converted it to CSV.  The output from the process is shown below.

[root@server ~]# **csvtotable t.csv t.html**
Aborted!
[root@server ~]# **more t.csv**
ABC,12.34,T,1
ABC,12.31,F,2
ABC,12.40,T,3
ABC,12.32,T,4

BTW, I am running CentOS 7, with Python development kit, patched, and latest updates (via yum).  There were **no errors** during the install.

**Comment by abbazabba** [comment]
I was getting it also using release 1.1.2.

Workaround by using -o option even though there is nothing to overwrite.

**Comment by vividvilla** [comment]
Thanks for reporting. Please update to version `1.1.3` in which this bug is fixed. 

    pip install --upgrade csvtotable
